### ISSUE TITLE
How to train SVR in A Lightweight YOLOv2 paper. 

### ISSUE THREAD

**Issue by ghimiredhikura** [HirokiNakahara/GUINNESS#10]
Hello @HirokiNakahara, 

I was following your paper [A Lightweight YOLOv2 ](https://dl.acm.org/citation.cfm?id=3174266). But while training SVR I am facing some difficulties. Will you kindly clarify following things. 
1. How did you prepare training dataset for SVR. Did you take binary output from each cell from the last conv layer? If yes, what was the target values in the cell where non of the GT object falls. 
2. In some cell, if the center of the GT box lies, how did you take x, y, dx, dy, conf and probabilities for training 55 SVR? 

Thanks. 

Best,
Deepak

**Comment by HirokiNakahara** [comment]
Hi Deepak,

This repository is a binary neural network development, not for the mixed precision one including binary CNN with an SVR. I think your question is the out of this repository.

Additionally, I cannot open more detail training techniques, because we are obligated to keep it secret with vendors.

Regards,
Hiroki
